"""
Rumble OS Master Schemas.

Defines the multi-domain `MasterLifeBrief`, `LifeAlert`, `ActionItemRecord`, `SymptomPainState`,
and supporting models that aggregate Daily Operations, CMO Medical Advisories, and Symptom Tracking
into a unified structured contract for downstream persistence, alert evaluation, and UI display.
"""

from __future__ import annotations

from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field

from src.schemas.medical import PersonalAdvisorBrief
from src.schemas.ops import BriefingReport, SpoonState


class AlertSeverity(str, Enum):
    CRITICAL = "Critical"
    HIGH = "High"
    INFO = "Info"


class AlertCategory(str, Enum):
    MEDICAL = "Medical"
    OPS = "Operations"
    SYMPTOMS = "Symptoms/Pain"
    FINANCE = "Finance"


class ActionCategory(str, Enum):
    ALERT = "Alert"
    SYMPTOMS = "Symptoms/Pain"
    MEDICAL = "Medical"
    OPS = "Operations"


class SymptomPainState(BaseModel):
    """Anatomical Pain & Symptom Tracking Snapshot (9 AM, 12 PM, 3 PM, 9 PM)."""

    id: Optional[int] = Field(default=None, description="Database record ID")
    timestamp: str = Field(..., description="ISO 8601 UTC timestamp")
    date: str = Field(..., description="Date string (YYYY-MM-DD)")
    time_slot: str = Field(..., description="Target time slot: '9:00 AM', '12:00 PM', '3:00 PM', '9:00 PM'")
    total_pain_level: int = Field(..., ge=1, le=10, description="Overall pain scale rating 1-10")
    primary_generator: str = Field(
        default="Right Lumbar Pain",
        description="Primary anatomical pain generator location (e.g. 'Right Lumbar Pain')",
    )
    primary_percentage: int = Field(
        default=85,
        ge=0,
        le=100,
        description="Percentage of total pain generated by primary location (e.g. 85%)",
    )
    active_symptoms: list[str] = Field(
        default_factory=list,
        description="List of selected hotkey symptoms (e.g. ['Right Lumbar Pain', 'Cervical Spine Pain', 'Right Shoulder Pain', 'Left Knee Pain', 'Right Ankle Pain', 'Thoracic Spine Pain'])",
    )
    notes: Optional[str] = Field(default="", description="Additional clinical notes or context for doctor reports")


class LifeAlert(BaseModel):
    """Represents an actionable alert generated by rule or LLM assessment."""

    id: Optional[str] = Field(default=None, description="Unique alert identifier")
    timestamp: str = Field(..., description="ISO timestamp when alert was triggered")
    severity: AlertSeverity = Field(..., description="Alert severity level")
    category: AlertCategory = Field(..., description="Domain category of the alert")
    title: str = Field(..., description="Short descriptive title of the alert")
    summary: str = Field(..., description="Detailed body/context explanation")
    action_required: str = Field(..., description="Explicit next step required to resolve")
    resolved: bool = Field(default=False, description="Whether alert has been actioned/resolved")


class ActionItemRecord(BaseModel):
    """Structured daily action item with persistent state and domain routing."""

    id: str = Field(..., description="Unique action item ID")
    text: str = Field(..., description="Action item description text")
    category: ActionCategory = Field(default=ActionCategory.OPS, description="Domain category")
    completed: bool = Field(default=False, description="Completion status")
    linked_id: Optional[str] = Field(default=None, description="Optional linked Alert or Event ID")


class MasterLifeBrief(BaseModel):
    """
    Root multi-domain brief generated by ChiefRumbleOfficer orchestrator.
    Consolidates Daily Ops, Medical Hubs, and Symptom Pain Tracking.
    """

    id: Optional[int] = Field(default=None, description="Database record ID")
    timestamp: str = Field(..., description="ISO 8601 UTC timestamp")
    date: str = Field(..., description="Date string (YYYY-MM-DD)")
    headline_summary: str = Field(
        ...,
        description="Top-level executive summary summarizing the user's day across ops, health, and symptoms.",
    )
    active_alerts: list[LifeAlert] = Field(
        default_factory=list,
        description="Prioritized list of active alerts requiring attention.",
    )
    ops_briefing: BriefingReport = Field(
        ...,
        description="Daily operations, schedule, tickets, and emails report.",
    )
    medical_briefing: Optional[PersonalAdvisorBrief] = Field(
        default=None,
        description="CMO medical & rehab advisory synthesis (if applicable for today).",
    )
    symptom_state: SymptomPainState = Field(
        ...,
        description="Anatomical Symptom & Pain Tracking snapshot.",
    )
    consolidated_action_items: list[str] = Field(
        default_factory=list,
        description="Ranked single list of string action items across all domains.",
    )
    action_records: list[ActionItemRecord] = Field(
        default_factory=list,
        description="Structured action item records with backend routing.",
    )
